export class Milp_parameters {
    
    constructor(public id?: number,
        public min_voltage_pu?: number,
        public max_voltage_pu?: number,
        public nominal_voltage_kv?: number,
        public num_blocks_linearization?: number,
        public pcc_cost_t01?: number,
        public pcc_cost_t02?: number,
        public pcc_cost_t03?: number,
        public pcc_cost_t04?: number,
        public pcc_cost_t05?: number,
        public pcc_cost_t06?: number,
        public pcc_cost_t07?: number,
        public pcc_cost_t08?: number,
        public pcc_cost_t09?: number,
        public pcc_cost_t10?: number,
        public pcc_cost_t11?: number,
        public pcc_cost_t12?: number,
        public pcc_cost_t13?: number,
        public pcc_cost_t14?: number,
        public pcc_cost_t15?: number,
        public pcc_cost_t16?: number,
        public pcc_cost_t17?: number,
        public pcc_cost_t18?: number,
        public pcc_cost_t19?: number,
        public pcc_cost_t20?: number,
        public pcc_cost_t21?: number,
        public pcc_cost_t22?: number,
        public pcc_cost_t23?: number,
        public pcc_cost_t24?: number,
        public load_pred_error?: number,
        public pv_generation_pred_error?: number,
        public genset_cost?: number,
        public max_power_pcc_kw?: number,
        public load_curt_cost?: number){}
}