from sqlalchemy import func
from api_tools.db import db
from datetime import datetime


class node_information_model(db.Model):
    __tablename__='node_information_table'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    type = db.Column(db.String(50), default='PQ')
    der = db.Column(db.String(50), default='none')
    nominal_kva = db.Column(db.Float(precision=2), default=0.0)
    minimum_kva = db.Column(db.Float(precision=2), default=0.0)
    maximum_kva = db.Column(db.Float(precision=2), default=0.0)
    power_factor = db.Column(db.Float(precision=2), default=1.0)
    soc_min_bat = db.Column(db.Float(precision=2), default=0.0)
    soc_max_bat = db.Column(db.Float(precision=2), default=1.0)
    bat_nom_energy = db.Column(db.Float(precision=2), default=0.0)
    soc_min_ev = db.Column(db.Float(precision=2), default=0.0)
    soc_max_ev = db.Column(db.Float(precision=2), default=1.0)

    medidas_no = db.relationship('node_measurement_model', lazy='dynamic', cascade="all, delete-orphan")
    
class node_measurement_model(db.Model):
    __tablename__='node_measurement_table'
    id = db.Column(db.Integer, primary_key=True)
    time_iso = db.Column(db.DateTime)
    active_power_a_kw = db.Column(db.Float(precision=2), default=0.0)
    active_power_b_kw = db.Column(db.Float(precision=2), default=0.0)
    active_power_c_kw = db.Column(db.Float(precision=2), default=0.0)
    reactive_power_a_kvar = db.Column(db.Float(precision=2), default=0.0)
    reactive_power_b_kvar = db.Column(db.Float(precision=2), default=0.0)
    reactive_power_c_kvar = db.Column(db.Float(precision=2), default=0.0)
    voltage_a_kv = db.Column(db.Float(precision=2), default=0.0)
    voltage_b_kv = db.Column(db.Float(precision=2), default=0.0)
    voltage_c_kv = db.Column(db.Float(precision=2), default=0.0)
    soc_kwh = db.Column(db.Float(precision=2), default=0.0)
    # soc_ev_1_kwh = db.Column(db.Float(precision=2), default=0.0)
    # soc_ev_2_kwh = db.Column(db.Float(precision=2), default=0.0)
    id_info_no = db.Column(db.Integer, db.ForeignKey('node_information_table.id'))

class branch_information_model(db.Model):
    __tablename__='branch_information_table'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    initial_node = db.Column(db.String(50))
    end_node = db.Column(db.String(50))
    resistance_aa = db.Column(db.Float(precision=4), default=0.0)
    resistance_bb = db.Column(db.Float(precision=4), default=0.0)
    resistance_cc = db.Column(db.Float(precision=4), default=0.0)
    resistance_ab = db.Column(db.Float(precision=2), default=0.0)
    resistance_ac = db.Column(db.Float(precision=2), default=0.0)
    resistance_bc = db.Column(db.Float(precision=2), default=0.0)
    reactance_aa = db.Column(db.Float(precision=4), default=0.0)
    reactance_bb = db.Column(db.Float(precision=4), default=0.0)
    reactance_cc = db.Column(db.Float(precision=4), default=0.0)
    reactance_ab = db.Column(db.Float(precision=2), default=0.0)
    reactance_ac = db.Column(db.Float(precision=2), default=0.0)
    reactance_bc = db.Column(db.Float(precision=2), default=0.0)
    max_current = db.Column(db.Float(precision=2), default=0.0)
    medidas_ramo = db.relationship('branch_measurement_model', lazy='dynamic', cascade="all, delete-orphan")

class branch_measurement_model(db.Model):
    __tablename__='branch_measurement_table'
    id = db.Column(db.Integer, primary_key=True)
    time_iso = db.Column(db.DateTime)
    active_power_flow_a_kw = db.Column(db.Float(precision=2), default=0.0)
    active_power_flow_b_kw = db.Column(db.Float(precision=2), default=0.0)
    active_power_flow_c_kw = db.Column(db.Float(precision=2), default=0.0)
    reactive_power_flow_a_kvar = db.Column(db.Float(precision=2), default=0.0)
    reactive_power_flow_b_kvar = db.Column(db.Float(precision=2), default=0.0)
    reactive_power_flow_c_kvar = db.Column(db.Float(precision=2), default=0.0)
    current_a_A = db.Column(db.Float(precision=2), default=0.0)
    current_b_A = db.Column(db.Float(precision=2), default=0.0)
    current_c_A = db.Column(db.Float(precision=2), default=0.0)
    id_info_ramo = db.Column(db.Integer, db.ForeignKey('branch_information_table.id'))

class economic_dispatch_model(db.Model):
    __tablename__='economic_dispatch_table'
    id = db.Column(db.Integer, primary_key=True)
    bat_power_t00 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t01 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t02 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t03 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t04 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t05 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t06 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t07 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t08 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t09 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t10 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t11 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t12 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t13 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t14 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t15 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t16 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t17 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t18 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t19 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t20 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t21 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t22 = db.Column(db.Float(precision=2), default=0.0)
    bat_power_t23 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t00 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t01 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t02 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t03 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t04 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t05 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t06 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t07 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t08 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t09 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t10 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t11 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t12 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t13 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t14 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t15 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t16 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t17 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t18 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t19 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t20 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t21 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t22 = db.Column(db.Float(precision=2), default=0.0)
    genset_power_t23 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t00 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t01 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t02 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t03 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t04 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t05 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t06 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t07 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t08 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t09 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t10 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t11 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t12 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t13 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t14 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t15 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t16 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t17 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t18 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t19 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t20 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t21 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t22 = db.Column(db.Float(precision=2), default=0.0)
    load_curt_t23 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t00 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t01 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t02 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t03 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t04 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t05 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t06 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t07 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t08 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t09 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t10 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t11 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t12 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t13 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t14 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t15 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t16 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t17 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t18 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t19 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t20 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t21 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t22 = db.Column(db.Float(precision=2), default=0.0)
    pv_curt_t23 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t00 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t01 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t02 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t03 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t04 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t05 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t06 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t07 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t08 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t09 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t10 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t11 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t12 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t13 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t14 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t15 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t16 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t17 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t18 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t19 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t20 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t21 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t22 = db.Column(db.Float(precision=2), default=0.0)
    ev_1_power_t23 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t00 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t01 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t02 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t03 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t04 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t05 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t06 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t07 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t08 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t09 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t10 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t11 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t12 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t13 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t14 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t15 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t16 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t17 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t18 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t19 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t20 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t21 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t22 = db.Column(db.Float(precision=2), default=0.0)
    ev_2_power_t23 = db.Column(db.Float(precision=2), default=0.0)

class milp_parameters_model(db.Model):
    __tablename__='milp_parameters_table'
    id = db.Column(db.Integer, primary_key=True)
    min_voltage_pu = db.Column(db.Float(precision=2), default=0.9)
    max_voltage_pu = db.Column(db.Float(precision=2), default=1.0)
    nominal_voltage_kv = db.Column(db.Float(precision=2), default=0.22)
    num_blocks_linearization = db.Column(db.Integer, default=20)
    pcc_cost_t01 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t02 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t03 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t04 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t05 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t06 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t07 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t08 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t09 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t10 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t11 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t12 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t13 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t14 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t15 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t16 = db.Column(db.Float(precision=3), default=0.250)
    pcc_cost_t17 = db.Column(db.Float(precision=3), default=0.250)
    pcc_cost_t18 = db.Column(db.Float(precision=3), default=0.420)
    pcc_cost_t19 = db.Column(db.Float(precision=3), default=0.420)
    pcc_cost_t20 = db.Column(db.Float(precision=3), default=0.420)
    pcc_cost_t21 = db.Column(db.Float(precision=3), default=0.250)
    pcc_cost_t22 = db.Column(db.Float(precision=3), default=0.250)
    pcc_cost_t23 = db.Column(db.Float(precision=3), default=0.145)
    pcc_cost_t24 = db.Column(db.Float(precision=3), default=0.145)
    load_pred_error = db.Column(db.Float(precision=4), default=0.0)
    pv_generation_pred_error = db.Column(db.Float(precision=4), default=0.0)
    genset_cost = db.Column(db.Float(precision=2), default=0.5)
    max_power_pcc_kw = db.Column(db.Float(precision=2), default=100)
    load_curt_cost = db.Column(db.Float(precision=2), default=500)

class ev_parameters_model(db.Model):
    __tablename__='ev_parameters_table'
    id = db.Column(db.Integer, primary_key=True)
    EV_battery_size_1 = db.Column(db.Float(precision=2), default=0.0)
    EV_power_size_1 = db.Column(db.Float(precision=2), default=0.0)
    EV_initial_SoC_1 = db.Column(db.Float(precision=2), default=0.0)
    EV_arrival_time_1 = db.Column(db.Integer, default=10)
    EV_departure_time_1 = db.Column(db.Integer, default=10)
    EV_battery_size_2 = db.Column(db.Float(precision=2), default=0.0)
    EV_power_size_2 = db.Column(db.Float(precision=2), default=0.0)
    EV_initial_SoC_2 = db.Column(db.Float(precision=2), default=0.0)
    EV_arrival_time_2 = db.Column(db.Integer, default=10)
    EV_departure_time_2 = db.Column(db.Integer, default=10)